export {default as Account} from './Account/Account'
export {default as Cart} from './Cart/Cart'
export {default as HomePage} from './HomePage/HomePage'
export {default as MyOrders} from './MyOrders/MyOrder'
export {default as Offers} from './Offers/Offers'
export {default as Profile} from './Profile/Profile'
export {default as TrackOrders} from './TrackOrders/TrackOrder'
export {default as Product} from './ProductInfo/Product'
export {default as Wishlist} from './Wishlist/Wishlist'
export {default as ResetPassword} from './Authantication/ResetPassword'

